export enum Events {
  AUTH_FAILURE = 'AUTH_FAILURE',
  JWT_VIOLATION = 'JWT_VIOLATION',
  PRICE_MISMATCH = 'PRICE_MISMATCH',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  SUSPICIOUS_QR_ACCESS = 'SUSPICIOUS_QR_ACCESS',
  SUSPICIOUS_TABLE_ACCESS = 'SUSPICIOUS_TABLE_ACCESS',
  REQUEST = 'REQUEST',
}
